main_domain: "example.com"
site_for_each_organization: true
organizations:
  A:
    name: "A Organization"
  B:
    name: "B Organization"
microsites:
  $:
    context_overrides: {}
    overrides:
      ecommerce:
        ecommerce.core.models.SiteConfiguration:
          oauth_settings:
            SOCIAL_AUTH_EDX_OAUTH2_KEY: ecommerce-sso client id
            SOCIAL_AUTH_EDX_OAUTH2_SECRET: ecommerce-sso client secret
            BACKEND_SERVICE_EDX_OAUTH2_KEY: ecommerce-backend-service client id
            BACKEND_SERVICE_EDX_OAUTH2_SECRET: ecommerce-backend-service client secret
          payment_processors: paypal,cybersource

  A:
    overrides:
      lms:
        openedx.core.djangoapps.site_configuration.models.SiteConfiguration:
          site_values:
            PLATFORM_NAME: Something Special!
